controllers:
    resource: ../src/Shared/Infrastructure/Controller/
    type: attribute

url_shortener:
    resource: ../src/UrlShortener/Infrastructure/Controller/
    type: annotation

analytic:
    resource: ../src/Analytic/Infrastructure/Controller/
    type: annotation